export const assetCategories = [
    {
        label: "Crypto",
        options: [
            { value: "BTCUSD", label: "Bitcoin (BTCUSD)" },
            { value: "ETHUSD", label: "Ethereum (ETHUSD)" },
            { value: "SOLUSD", label: "Solana (SOLUSD)" },
            { value: "XRPUSD", label: "XRP (XRPUSD)" },
            { value: "LTCUSD", label: "Litecoin (LTCUSD)" },
            { value: "BCHUSD", label: "Bitcoin Cash (BCHUSD)" },
            { value: "DOGEUSD", label: "Dogecoin (DOGEUSD)" },
            { value: "BNBUSD", label: "BNB (BNBUSD)" },
            { value: "USDTUSD", label: "Tether (USDTUSD)" },
        ],
    },
    {
        label: "Indices",
        options: [
            { value: "INX", label: "S&P 500 (INX)" },
            { value: "NDX", label: "NASDAQ 100 (NDX / US100)" },
            { value: "DJI", label: "Dow Jones (DJI / US30)" },
            { value: "UK100", label: "FTSE 100 (UK100)" },
            { value: "GER40", label: "DAX (GER40)" },
            { value: "AUS200", label: "AUS200" },
            { value: "EUSTX50", label: "EUSTX50" },
            { value: "FRA40", label: "FRA40" },
            { value: "HK50", label: "Hang Seng (HK50)" },
            { value: "JPN225", label: "Nikkei 225 (JPN225)" },
            { value: "SPA35", label: "SPA35" },
            { value: "SWI20", label: "SWI20" },
            { value: "DXY", label: "U.S. Dollar Index (DXY)" },
            { value: "US2000", label: "US2000" },
        ],
    },
    {
        label: "Forex",
        options: [
            { value: "AUDCAD", label: "AUD/CAD" },
            { value: "AUDCHF", label: "AUD/CHF" },
            { value: "AUDJPY", label: "AUD/JPY" },
            { value: "AUDNZD", label: "AUD/NZD" },
            { value: "AUDSGD", label: "AUD/SGD" },
            { value: "AUDUSD", label: "AUD/USD" },
            { value: "CADCHF", label: "CAD/CHF" },
            { value: "CADJPY", label: "CAD/JPY" },
            { value: "CHFJPY", label: "CHF/JPY" },
            { value: "CHFSGD", label: "CHF/SGD" },
            { value: "EURAUD", label: "EUR/AUD" },
            { value: "EURCAD", label: "EUR/CAD" },
            { value: "EURCHF", label: "EUR/CHF" },
            { value: "EURCZK", label: "EUR/CZK" },
            { value: "EURGBP", label: "EUR/GBP" },
            { value: "EURHKD", label: "EUR/HKD" },
            { value: "EURILS", label: "EUR/ILS" },
            { value: "EURJPY", label: "EUR/JPY" },
            { value: "EURNZD", label: "EUR/NZD" },
            { value: "EURRON", label: "EUR/RON" },
            { value: "EURRUB", label: "EUR/RUB" },
            { value: "EURSGD", label: "EUR/SGD" },
            { value: "EURTRY", label: "EUR/TRY" },
            { value: "EURUSD", label: "EUR/USD" },
            { value: "EURZAR", label: "EUR/ZAR" },
            { value: "GBPAUD", label: "GBP/AUD" },
            { value: "GBPCAD", label: "GBP/CAD" },
            { value: "GBPCHF", label: "GBP/CHF" },
            { value: "GBPCZK", label: "GBP/CZK" },
            { value: "GBPHKD", label: "GBP/HKD" },
            { value: "GBPJPY", label: "GBP/JPY" },
            { value: "GBPNZD", label: "GBP/NZD" },
            { value: "GBPSGD", label: "GBP/SGD" },
            { value: "GBPTRY", label: "GBP/TRY" },
            { value: "GBPUSD", label: "GBP/USD" },
            { value: "GBPZAR", label: "GBP/ZAR" },
            { value: "NZDCAD", label: "NZD/CAD" },
            { value: "NZDCHF", label: "NZD/CHF" },
            { value: "NZDJPY", label: "NZD/JPY" },
            { value: "NZDSGD", label: "NZD/SGD" },
            { value: "NZDUSD", label: "NZD/USD" },
            { value: "SGDJPY", label: "SGD/JPY" },
            { value: "USDCAD", label: "USD/CAD" },
            { value: "USDCHF", label: "USD/CHF" },
            { value: "USDCNH", label: "USD/CNH" },
            { value: "USDCZK", label: "USD/CZK" },
            { value: "USDDKK", label: "USD/DKK" },
            { value: "USDHKD", label: "USD/HKD" },
            { value: "USDHUF", label: "USD/HUF" },
            { value: "USDILS", label: "USD/ILS" },
            { value: "USDJPY", label: "USD/JPY" },
            { value: "USDMXN", label: "USD/MXN" },
            { value: "USDNOK", label: "USD/NOK" },
            { value: "USDPLN", label: "USD/PLN" },
            { value: "USDRON", label: "USD/RON" },
            { value: "USDRUB", label: "USD/RUB" },
            { value: "USDSEK", label: "USD/SEK" },
            { value: "USDSGD", label: "USD/SGD" },
            { value: "USDTHB", label: "USD/THB" },
            { value: "USDZAR", label: "USD/ZAR" },
            { value: "ZARJPY", label: "ZAR/JPY" },
        ],
    },
    {
        label: "Commodities",
        options: [
            { value: "XAUUSD", label: "Gold (XAU/USD)" },
            { value: "XAGUSD", label: "Silver (XAG/USD)" },
            { value: "USOIL", label: "WTI Crude Oil (USOIL)" },
            { value: "UKOIL", label: "Brent Crude Oil (UKOIL)" },
            { value: "XNGUSD", label: "Natural Gas (XNG/USD)" },
            { value: "XAUEUR", label: "Gold (XAU/EUR)" },
            { value: "XAUJPY", label: "Gold (XAU/JPY)" },
            { value: "XAGEUR", label: "Silver (XAG/EUR)" },
            { value: "USBKT", label: "US Oil Basket (USBKT)" },
        ],
    },
];
